# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"
import "./lib/tasks/server.rake"
import "./lib/tasks/cucumber.rake"

RSpec::Core::RakeTask.new(:spec)

task default: :spec
